language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_8cdf27954842_key -iv $encrypted_8cdf27954842_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d

